MOCK_POSTS = {
  "posts": [
    {
      "id": "post_001",
      "caption": "🚀 Transform your business with AI! Our latest automation solutions have helped clients increase productivity by 40%. Ready to join the AI revolution? Let's chat! #AIConsulting #BusinessAutomation #DigitalTransformation #TechSolutions #Innovation",
      "day": "Monday",
      "scheduledTime": "09:00 AM",
      "likes": 127,
      "comments": 15,
      "shares": 8,
      "isPublished": 1,
      "platform": "LinkedIn",
      "postType": "promotional",
      "engagement_rate": 8.5,
      "scheduled_this_week": 1
    },
    {
      "id": "post_002",
      "caption": "💡 Pro Tip Tuesday: Did you know that 67% of small businesses still don't have a mobile-responsive website? In 2024, mobile-first design isn't optional—it's essential! 📱✨ #WebDevelopment #MobileFriendly #TechTips #WebDesign #ResponsiveDesign",
      "day": "Tuesday",
      "scheduledTime": "02:30 PM",
      "likes": 89,
      "comments": 12,
      "shares": 5,
      "isPublished": 0,
      "platform": "Instagram",
      "postType": "tip",
      "engagement_rate": 6.2,
      "scheduled_this_week": 1
    },
    {
      "id": "post_003",
      "caption": "🎉 EXCITING NEWS! We just launched our new Cloud Migration service! Help your business save 30% on infrastructure costs while boosting performance. Early bird discount available this week only! 🌟 DM us for details. #CloudMigration #CostSaving #BusinessGrowth",
      "day": "Wednesday",
      "scheduledTime": "11:15 AM",
      "likes": 203,
      "comments": 28,
      "shares": 15,
      "isPublished": 0,
      "platform": "Facebook",
      "postType": "promotional",
      "engagement_rate": 0,
      "scheduled_this_week": 1
    },
    {
      "id": "post_004",
      "caption": "🔒 Cybersecurity Alert: With cyber threats increasing by 25% this year, protecting your business data is more critical than ever. Here are 3 essential security measures every SMB should implement: 1️⃣ Multi-factor authentication 2️⃣ Regular software updates 3️⃣ Employee training programs. Stay safe! #Cybersecurity #DataProtection #BusinessSecurity #SMBSafety",
      "day": "Thursday",
      "scheduledTime": "10:00 AM",
      "likes": 156,
      "comments": 22,
      "shares": 18,
      "isPublished": 1,
      "platform": "LinkedIn",
      "postType": "tip",
      "engagement_rate": 9.1,
      "scheduled_this_week": 1
    },
    {
      "id": "post_005",
      "caption": "✨ Friday Feature: Meet Sarah, a local bakery owner who transformed her business with our e-commerce solution! From 20 orders/week to 200+ orders/week in just 3 months. 🍰📈 What's stopping you from going digital? #ClientSuccess #EcommerceSolutions #DigitalTransformation #SmallBusiness #FridayFeature",
      "day": "Friday",
      "scheduledTime": "03:45 PM",
      "likes": 94,
      "comments": 8,
      "shares": 6,
      "isPublished": 0,
      "platform": "Instagram",
      "postType": "case_study",
      "engagement_rate": 7.3,
      "scheduled_this_week": 1
    },
    {
      "id": "post_006",
      "caption": "🌟 Weekend Wisdom: 'The best time to plant a tree was 20 years ago. The second best time is now.' The same applies to digital transformation! Don't wait for the 'perfect moment'—start your tech journey today. 💪 #WeekendWisdom #DigitalTransformation #TechJourney #Motivation #BusinessGrowth",
      "day": "Saturday",
      "scheduledTime": "12:00 PM",
      "likes": 67,
      "comments": 5,
      "shares": 3,
      "isPublished": 0,
      "platform": "Facebook",
      "postType": "inspirational",
      "engagement_rate": 0,
      "scheduled_this_week": 1
    },
    {
      "id": "post_007",
      "caption": "🔄 Sunday Update: This week we helped 3 new businesses migrate to cloud infrastructure, launched 2 AI chatbots, and completed 1 major website overhaul! Thank you to all our amazing clients for trusting us with your digital transformation. Ready for an even bigger week ahead! 💼✨ #SundayUpdate #WeeklyRecap #TechSolutions #ClientWork",
      "day": "Sunday",
      "scheduledTime": "06:00 PM",
      "likes": 78,
      "comments": 11,
      "shares": 4,
      "isPublished": 1,
      "platform": "LinkedIn",
      "postType": "update",
      "engagement_rate": 5.8,
      "scheduled_this_week": 1
    },
    {
      "id": "post_008",
      "caption": "⚡ BREAKING: Our AI-powered analytics tool just helped a client identify $50K in cost savings! Imagine what insights are hiding in your data. Ready to unlock them? 📊✨ #DataAnalytics #AIInsights #CostSavings #BusinessIntelligence #TechSolutions",
      "day": "Monday",
      "scheduledTime": "08:30 AM",
      "likes": 234,
      "comments": 31,
      "shares": 19,
      "isPublished": 1,
      "platform": "LinkedIn",
      "postType": "case_study",
      "engagement_rate": 12.1,
      "scheduled_this_week": 0
    },
    {
      "id": "post_009",
      "caption": "🎯 Tuesday Tip: Stop manually updating spreadsheets! Automation can handle 80% of your repetitive tasks. Our latest automation project saved a client 15 hours/week. What tasks are eating up your time? #AutomationTip #ProductivityHack #BusinessEfficiency #WorkSmarter",
      "day": "Tuesday",
      "scheduledTime": "01:00 PM",
      "likes": 167,
      "comments": 24,
      "shares": 12,
      "isPublished": 1,
      "platform": "Twitter",
      "postType": "tip",
      "engagement_rate": 9.8,
      "scheduled_this_week": 0
    },
    {
      "id": "post_010",
      "caption": "🔥 Monday Motivation: Your body can stand almost anything. It's your mind you have to convince! Start this week strong with our HIIT class at 6 AM. First session FREE for new members! 💪 #MondayMotivation #HIITWorkout #FitnessGoals #NewMemberSpecial #FitLifeGym",
      "day": "Monday",
      "scheduledTime": "05:45 AM",
      "likes": 312,
      "comments": 45,
      "shares": 28,
      "isPublished": 1,
      "platform": "Instagram",
      "postType": "motivational",
      "engagement_rate": 15.2,
      "scheduled_this_week": 0
    },
    {
      "id": "post_011",
      "caption": "🥗 Nutrition Wednesday: Post-workout meals matter! Try this simple protein-packed smoothie: 1 banana + 1 scoop protein powder + spinach + almond milk + chia seeds. Fuel your gains the right way! Recipe in our bio 📖 #NutritionWednesday #PostWorkout #ProteinSmoothie #HealthyRecipes #FuelYourBody",
      "day": "Wednesday",
      "scheduledTime": "07:30 AM",
      "likes": 289,
      "comments": 38,
      "shares": 52,
      "isPublished": 0,
      "platform": "Instagram",
      "postType": "educational",
      "engagement_rate": 18.7,
      "scheduled_this_week": 0
    },
    {
      "id": "post_012",
      "caption": "🌱 Farm Fresh Friday! Just received our weekly harvest from Green Valley Farm - organic tomatoes, basil, and arugula picked this morning! Tonight's special: Caprese salad with our homemade balsamic reduction. Limited quantities! 🍅 #FarmFresh #OrganicFood #TonightsSpecial #LocalFarm #SustainableDining",
      "day": "Friday",
      "scheduledTime": "04:00 PM",
      "likes": 445,
      "comments": 67,
      "shares": 34,
      "isPublished": 1,
      "platform": "Instagram",
      "postType": "promotional",
      "engagement_rate": 22.1,
      "scheduled_this_week": 1
    },
    {
      "id": "post_013",
      "caption": "☕ Sunday Brunch Vibes: Nothing beats our signature avocado toast with poached eggs and a perfectly brewed cortado. Join us this Sunday 10 AM - 3 PM for the ultimate brunch experience! Reservations recommended 📞 #SundayBrunch #AvocadoToast #CortadoCoffee #BrunchVibes #WeekendTreats",
      "day": "Sunday",
      "scheduledTime": "09:00 AM",
      "likes": 356,
      "comments": 42,
      "shares": 25,
      "isPublished": 0,
      "platform": "Facebook",
      "postType": "promotional",
      "engagement_rate": 0,
      "scheduled_this_week": 0
    },
    {
      "id": "post_014",
      "caption": "🏡 JUST LISTED! Stunning 3BR/2BA colonial in Maple Heights! Features: updated kitchen, hardwood floors, large backyard, 2-car garage. Perfect for growing families! Virtual tour available. Priced at $485K. DM for private showing! 🔑 #JustListed #MapleHeights #FamilyHome #VirtualTour #RealEstate",
      "day": "Thursday",
      "scheduledTime": "10:30 AM",
      "likes": 89,
      "comments": 15,
      "shares": 23,
      "isPublished": 1,
      "platform": "Facebook",
      "postType": "listing",
      "engagement_rate": 11.4,
      "scheduled_this_week": 1
    },
    {
      "id": "post_015",
      "caption": "📈 Market Monday: Interest rates dropped 0.25%! This could save buyers $200-300/month on a $400K home. Perfect time to make your move! Pre-approval letters available in 24 hours. Let's find your dream home! #MarketMonday #InterestRates #HomeBuying #PreApproval #DreamHome",
      "day": "Monday",
      "scheduledTime": "11:00 AM",
      "likes": 156,
      "comments": 28,
      "shares": 18,
      "isPublished": 0,
      "platform": "LinkedIn",
      "postType": "market_update",
      "engagement_rate": 8.9,
      "scheduled_this_week": 0
    },
    {
      "id": "post_016",
      "caption": "✨ Transformation Tuesday! Check out this gorgeous balayage by our senior stylist Emma! From dull brown to sun-kissed blonde perfection ☀️ Book your color consultation this week and get 20% off highlights! #TransformationTuesday #Balayage #HairColor #SunKissed #BookNow",
      "day": "Tuesday",
      "scheduledTime": "12:30 PM",
      "likes": 278,
      "comments": 34,
      "shares": 16,
      "isPublished": 1,
      "platform": "Instagram",
      "postType": "transformation",
      "engagement_rate": 16.8,
      "scheduled_this_week": 0
    },
    {
      "id": "post_017",
      "caption": "💅 Weekend Pampering Special! Mani + Pedi combo only $65 (reg. $85) this Saturday & Sunday! Includes nail art, cuticle care, and relaxing hand massage. Walk-ins welcome or book online! Perfect weekend treat 🌸 #WeekendSpecial #ManicurePedicure #NailArt #PamperYourself #WalkInsWelcome",
      "day": "Friday",
      "scheduledTime": "02:15 PM",
      "likes": 198,
      "comments": 22,
      "shares": 31,
      "isPublished": 0,
      "platform": "Instagram",
      "postType": "promotional",
      "engagement_rate": 0,
      "scheduled_this_week": 0
    },
    {
      "id": "post_018",
      "caption": "🚗 Service Saturday Special! Full synthetic oil change + 21-point inspection only $49.99! Our certified technicians will keep your car running smooth. No appointment needed - first come, first served! Open 8 AM - 4 PM #ServiceSaturday #OilChange #CarMaintenance #CertifiedTechs #NoApptNeeded",
      "day": "Saturday",
      "scheduledTime": "07:30 AM",
      "likes": 134,
      "comments": 18,
      "shares": 9,
      "isPublished": 0,
      "platform": "Facebook",
      "postType": "service_special",
      "engagement_rate": 7.2,
      "scheduled_this_week": 1
    },
    {
      "id": "post_019",
      "caption": "🎨 Creative Thursday: Behind the scenes of our latest brand identity project! From concept sketches to final logo - the design process is pure magic ✨ Swipe to see the transformation! Need a brand refresh? Let's create something amazing together! #CreativeThursday #BrandIdentity #DesignProcess #LogoDesign #BrandRefresh",
      "day": "Thursday",
      "scheduledTime": "03:00 PM",
      "likes": 145,
      "comments": 19,
      "shares": 11,
      "isPublished": 1,
      "platform": "Instagram",
      "postType": "behind_scenes",
      "engagement_rate": 10.3,
      "scheduled_this_week": 0
    },
    {
      "id": "post_020",
      "caption": "🌟 Customer Spotlight: Shoutout to Jennifer from downtown law firm! She says our virtual assistant service freed up 20 hours/week to focus on clients instead of admin tasks. What would you do with 20 extra hours? #CustomerSpotlight #VirtualAssistant #TimeManagement #ClientFocus #ProductivityBoost",
      "day": "Friday",
      "scheduledTime": "01:30 PM",
      "likes": 87,
      "comments": 13,
      "shares": 7,
      "isPublished": 0,
      "platform": "LinkedIn",
      "postType": "testimonial",
      "engagement_rate": 6.8,
      "scheduled_this_week": 0
    }
  ]
}